apiVersion: infrastructure.platform.io/v1alpha1
kind: XSecretsStore
metadata:
  name: demo-secrets-store
  namespace: platform-apps
spec:
  parameters:
    region: eu-west-1
    providerConfigRef: aws-provider
    kmsKeyType: SYMMETRIC_DEFAULT
    secretCount: 2
