apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composition-data-proc-v1
  labels:
    platform.io/template: data-proc
spec:
  compositeTypeRef:
    apiVersion: infrastructure.platform.io/v1alpha1
    kind: XInfrastructureRequest
  mode: Pipeline
  pipeline:
    - step: render-status
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: xr-status
            base:
              apiVersion: infrastructure.platform.io/v1alpha1
              kind: XInfrastructureRequest
              status:
                observed:
                  message: "composition-data-proc-v1 rendered"
            patches:
              - type: ToCompositeFieldPath
                fromFieldPath: "status.observed.message"
                toFieldPath: "status.observed.message"