apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xsecretsstores.infrastructure.platform.io
spec:
  group: infrastructure.platform.io
  names:
    kind: XSecretsStore
    plural: xsecretsstores
  scope: Namespaced
  defaultCompositionRef:
    name: secrets-aws
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - parameters
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      default: eu-west-1
                    providerConfigRef:
                      type: string
                      default: aws-provider
                    kmsKeyType:
                      type: string
                      default: SYMMETRIC_DEFAULT
                    secretCount:
                      type: integer
                      default: 1
                      minimum: 1
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                      description: "FinOps tags applied to all resources in this capability"
                  required:
                    - region
            status:
              type: object
              properties:
                kmsKeyArn:
                  type: string
