apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: secrets-aws
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: infrastructure.platform.io/v1alpha1
    kind: XSecretsStore
  mode: Pipeline
  pipeline:
    - step: render
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := .observed.composite.resource -}}
            {{- $params := $xr.spec.parameters -}}
            {{- $region := default "eu-west-1" $params.region -}}
            {{- $providerConfigRef := default "aws-provider" $params.providerConfigRef -}}
            {{- $kmsKeyType := default "SYMMETRIC_DEFAULT" $params.kmsKeyType -}}
            {{- $secretCount := int (default 1 $params.secretCount) -}}

            ---
            apiVersion: kms.aws.upbound.io/v1beta1
            kind: Key
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: kms-key
            spec:
              providerConfigRef:
                name: {{ $providerConfigRef | quote }}
              forProvider:
                region: {{ $region | quote }}
                tags:
                {{- with $xr.spec.parameters.tags }}
                {{- toYaml . | nindent 20 }}
                {{- end }}
                description: "Managed by Crossplane"
                keyUsage: ENCRYPT_DECRYPT
                customerMasterKeySpec: {{ $kmsKeyType | quote }}
                enableKeyRotation: true
                deletionWindowInDays: 30

            {{- range $i := until $secretCount }}
            ---
            apiVersion: secretsmanager.aws.upbound.io/v1beta1
            kind: Secret
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ printf "secret-%d" $i | quote }}
                crossplane.io/external-name: {{- if eq $secretCount 1 }} {{ printf "%s-secret" $xr.metadata.name | quote }} {{- else }} {{ printf "%s-secret-%d" $xr.metadata.name (add1 $i) | quote }} {{- end }}
            spec:
              providerConfigRef:
                name: {{ $providerConfigRef | quote }}
              forProvider:
                region: {{ $region | quote }}
                description: "Managed by Crossplane"
                kmsKeyIdSelector:
                  matchControllerRef: true
            {{- end }}

            {{- with (index .observed.resources "kms-key") }}
            {{- with .resource.status.atProvider.arn }}
            ---
            apiVersion: infrastructure.platform.io/v1alpha1
            kind: XSecretsStore
            status:
              kmsKeyArn: {{ . | quote }}
            {{- end }}
            {{- end }}
    - step: ready
      functionRef:
        name: function-auto-ready
