//go:build integration

// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 gatblau

package integration

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/gatblau/release-engine/internal/connector"
	connectortesting "github.com/gatblau/release-engine/internal/connector/testing"
	"github.com/gatblau/release-engine/internal/module/infra"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestInfraIntegration_FullLifecycleAndCrossplaneValidation(t *testing.T) {
	harness := NewIntegrationTestHarness(t)
	harness.RegisterModule(infra.NewLegacyModule())

	// Register and bind all required connector families
	fileGit, err := connectortesting.NewFileGitConnector(harness.TempDir)
	require.NoError(t, err)
	harness.RegisterConnector(fileGit)
	harness.BindFamily("git", fileGit.Key())

	// The infra module also needs policy and webhook families, but they're not used
	// in the current implementation beyond the initial phase 1 steps.
	// For this test to pass, we need to bind mock implementations.
	// Create minimal mocks that return success
	mockPolicy := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "policy")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"allowed":    true,
					"violations": []interface{}{},
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockPolicy)
	harness.BindFamily("policy", mockPolicy.Key())

	mockWebhook := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "webhook")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"status_code":   200,
					"response_body": "ok",
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockWebhook)
	harness.BindFamily("webhook", mockWebhook.Key())

	params := loadParamsFixture(t, "infra-k8s-app")
	// Add required parameters for the module
	params["infra_repo"] = "tenant-integration/checkout-prod"
	params["callback_url"] = "http://example.com/callback"
	params["job_id"] = "test-job-id"
	params["idempotency_key"] = "infra-it-lifecycle-1"

	// Create repository and status file BEFORE job runs so health polling succeeds
	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-integration/checkout-prod"})
	require.NoError(t, err)
	// Create a mock .status.yaml file that will be found by health polling
	// Calculate expected commit SHA that will be generated by fileGit connector
	// Format: "{repo}-{branch}-{filesWritten}" where filesWritten = 1 (single manifest)
	expectedCommitSHA := fmt.Sprintf("%s-%s-%d", "tenant-integration/checkout-prod", "main", 1)
	statusContent := fmt.Sprintf(`status: healthy
timestamp: %s
commit_sha: %s
resources:
  - type: cluster
    arn: arn:aws:eks:eu-west-1:123456789012:cluster/test-cluster
    id: test-cluster-id`, time.Now().Format(time.RFC3339), expectedCommitSHA)
	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-integration/checkout-prod",
		"path":      ".status.yaml",
		"content":   statusContent,
	})
	require.NoError(t, err)

	jobID := harness.CreateJob(JobOptions{
		TenantID:       "tenant-integration",
		PathKey:        infra.ModuleKey,
		IdempotencyKey: "infra-it-lifecycle-1",
		Params:         params,
	})

	// Start a background approval service that will approve steps as they appear
	approvalCtx, approvalCancel := context.WithCancel(context.Background())
	defer approvalCancel()

	approvalDone := make(chan struct{})
	go func() {
		defer close(approvalDone)
		ticker := time.NewTicker(100 * time.Millisecond)
		defer ticker.Stop()

		for {
			select {
			case <-approvalCtx.Done():
				return
			case <-ticker.C:
				harness.AutoApproveWaitingSteps(jobID)
			}
		}
	}()

	// Run scheduler in background until job completes
	schedulerCtx, schedulerCancel := context.WithCancel(context.Background())
	defer schedulerCancel()

	schedulerErrCh := make(chan error, 1)
	go func() {
		schedulerErrCh <- harness.Scheduler.Start(schedulerCtx)
	}()

	// Wait for job to succeed
	require.NoError(t, harness.WaitForJobState(jobID, "succeeded", 30*time.Second))

	// Stop scheduler and approval service
	schedulerCancel()
	approvalCancel()
	<-schedulerErrCh // Wait for scheduler to stop
	<-approvalDone   // Wait for approval service to stop

	state, attempt, err := harness.JobState(jobID)
	require.NoError(t, err)
	require.Equal(t, "succeeded", state)
	require.Equal(t, 1, attempt)

	manifest := fetchLatestManifestYAML(t, harness, jobID)
	require.NotEmpty(t, manifest)
	exportManifestForVisualValidation(t, "infra-k8s-app.manifest.yaml", manifest)

	validator := NewCrossplaneValidator(
		FieldPresenceRule{fields: []string{"apiVersion", "kind", "metadata", "spec"}},
		PlatformTenantLabelRule{},
		SpecRule{},
	)
	require.NoError(t, validator.ValidateYAML([]byte(manifest)))

	// Compare against golden file for regression protection
	AssertGoldenYAML(t, "infra-k8s-app", []byte(manifest))

	require.NoError(t, fileGit.Validate("create_repository", map[string]interface{}{"repo_path": "tenant-integration/checkout-prod"}))
	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-integration/checkout-prod"})
	require.NoError(t, err)

	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-integration/checkout-prod",
		"path":      "infra/manifest.yaml",
		"content":   manifest,
	})
	require.NoError(t, err)

	res, err := fileGit.Execute(context.Background(), "get_file", map[string]interface{}{
		"repo_path": "tenant-integration/checkout-prod",
		"path":      "infra/manifest.yaml",
	})
	require.NoError(t, err)
	require.Equal(t, manifest, res.Output["content"])
}

func TestInfraIntegration_IdempotencyOnRetry(t *testing.T) {
	harness := NewIntegrationTestHarness(t)
	harness.RegisterModule(infra.NewLegacyModule())

	fileGit, err := connectortesting.NewFileGitConnector(harness.TempDir)
	require.NoError(t, err)
	harness.RegisterConnector(fileGit)
	harness.BindFamily("git", fileGit.Key())

	// Add mock policy and webhook connectors
	mockPolicy := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "policy")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"allowed":    true,
					"violations": []interface{}{},
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockPolicy)
	harness.BindFamily("policy", mockPolicy.Key())

	mockWebhook := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "webhook")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"status_code":   200,
					"response_body": "ok",
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockWebhook)
	harness.BindFamily("webhook", mockWebhook.Key())

	params := loadParamsFixture(t, "infra-k8s-app")
	// Add required parameters for the module
	params["infra_repo"] = "tenant-retry/checkout-prod"
	params["callback_url"] = "http://example.com/callback"
	params["job_id"] = "test-job-id"
	params["idempotency_key"] = "infra-it-retry-1"

	// Create repository and status file BEFORE job runs so health polling succeeds
	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-retry/checkout-prod"})
	require.NoError(t, err)
	// Create a mock .status.yaml file that will be found by health polling
	// Calculate expected commit SHA that will be generated by fileGit connector
	// Format: "{repo}-{branch}-{filesWritten}" where filesWritten = 1 (single manifest)
	expectedCommitSHA := fmt.Sprintf("%s-%s-%d", "tenant-retry/checkout-prod", "main", 1)
	statusContent := fmt.Sprintf(`status: healthy
timestamp: %s
commit_sha: %s
resources:
  - type: cluster
    arn: arn:aws:eks:eu-west-1:123456789012:cluster/test-cluster
    id: test-cluster-id`, time.Now().Format(time.RFC3339), expectedCommitSHA)
	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-retry/checkout-prod",
		"path":      ".status.yaml",
		"content":   statusContent,
	})
	require.NoError(t, err)

	jobID := harness.CreateJob(JobOptions{
		TenantID:       "tenant-retry",
		PathKey:        infra.ModuleKey,
		IdempotencyKey: "infra-it-retry-1",
		Params:         params,
	})

	require.NoError(t, harness.RunSchedulerCycle())
	require.NoError(t, harness.WaitForJobState(jobID, "succeeded", 5*time.Second))
	firstManifest := fetchLatestManifestYAML(t, harness, jobID)

	requeueJobForRetry(t, harness, jobID)
	require.NoError(t, harness.RunSchedulerCycle())
	require.NoError(t, harness.WaitForJobState(jobID, "succeeded", 5*time.Second))

	state, attempt, err := harness.JobState(jobID)
	require.NoError(t, err)
	require.Equal(t, "succeeded", state)
	require.Equal(t, 2, attempt)

	secondManifest := fetchLatestManifestYAML(t, harness, jobID)
	require.Equal(t, firstManifest, secondManifest, "manifest must stay stable across retries")

	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-retry/checkout-prod"})
	require.NoError(t, err)

	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-retry/checkout-prod",
		"path":      "infra/manifest.yaml",
		"content":   firstManifest,
	})
	require.NoError(t, err)

	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-retry/checkout-prod",
		"path":      "infra/manifest.yaml",
		"content":   secondManifest,
	})
	require.NoError(t, err)

	res, err := fileGit.Execute(context.Background(), "get_file", map[string]interface{}{
		"repo_path": "tenant-retry/checkout-prod",
		"path":      "infra/manifest.yaml",
	})
	require.NoError(t, err)
	require.Equal(t, secondManifest, res.Output["content"])
}

func TestInfraIntegration_DataProcTemplate(t *testing.T) {
	harness := NewIntegrationTestHarness(t)
	harness.RegisterModule(infra.NewLegacyModule())

	fileGit, err := connectortesting.NewFileGitConnector(harness.TempDir)
	require.NoError(t, err)
	harness.RegisterConnector(fileGit)
	harness.BindFamily("git", fileGit.Key())

	// Add mock policy and webhook connectors
	mockPolicy := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "policy")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"allowed":    true,
					"violations": []interface{}{},
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockPolicy)
	harness.BindFamily("policy", mockPolicy.Key())

	mockWebhook := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "webhook")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"status_code":   200,
					"response_body": "ok",
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockWebhook)
	harness.BindFamily("webhook", mockWebhook.Key())

	params := loadParamsFixture(t, "infra-data-proc")
	// Add required parameters for the module
	params["infra_repo"] = "tenant-data-proc/pipeline"
	params["callback_url"] = "http://example.com/callback"
	params["job_id"] = "test-job-id"
	params["idempotency_key"] = "infra-it-data-proc-1"

	// Create repository and status file BEFORE job runs so health polling succeeds
	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-data-proc/pipeline"})
	require.NoError(t, err)
	// Create a mock .status.yaml file that will be found by health polling
	// Calculate expected commit SHA that will be generated by fileGit connector
	// Format: "{repo}-{branch}-{filesWritten}" where filesWritten = 1 (single manifest)
	expectedCommitSHA := fmt.Sprintf("%s-%s-%d", "tenant-data-proc/pipeline", "main", 1)
	statusContent := fmt.Sprintf(`status: healthy
timestamp: %s
commit_sha: %s
resources:
  - type: cluster
    arn: arn:aws:eks:eu-west-1:123456789012:cluster/test-cluster
    id: test-cluster-id`, time.Now().Format(time.RFC3339), expectedCommitSHA)
	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-data-proc/pipeline",
		"path":      ".status.yaml",
		"content":   statusContent,
	})
	require.NoError(t, err)

	jobID := harness.CreateJob(JobOptions{
		TenantID:       "tenant-data-proc",
		PathKey:        infra.ModuleKey,
		IdempotencyKey: "infra-it-data-proc-1",
		Params:         params,
	})

	require.NoError(t, harness.RunSchedulerCycle())
	require.NoError(t, harness.WaitForJobState(jobID, "succeeded", 5*time.Second))

	manifest := fetchLatestManifestYAML(t, harness, jobID)
	exportManifestForVisualValidation(t, "infra-data-proc.manifest.yaml", manifest)

	validator := NewCrossplaneValidator(
		FieldPresenceRule{fields: []string{"apiVersion", "kind", "metadata", "spec"}},
		PlatformTenantLabelRule{},
		SpecRule{},
	)
	require.NoError(t, validator.ValidateYAML([]byte(manifest)))
	require.Contains(t, manifest, "kind: XKubernetesCluster")
	require.Contains(t, manifest, "kind: XMessaging")
	require.Contains(t, manifest, "kind: XObjectStore")
	require.Contains(t, manifest, "name: kubernetes-aws")
	require.Contains(t, manifest, "name: messaging-aws")
	require.Contains(t, manifest, "name: objectstorage-aws")

	// Compare against golden file for regression protection
	AssertGoldenYAML(t, "infra-data-proc", []byte(manifest))

	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-data-proc/pipeline"})
	require.NoError(t, err)
	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-data-proc/pipeline",
		"path":      "infra/manifest.yaml",
		"content":   manifest,
	})
	require.NoError(t, err)
}

func TestInfraIntegration_VMAppTemplate(t *testing.T) {
	harness := NewIntegrationTestHarness(t)
	harness.RegisterModule(infra.NewLegacyModule())

	fileGit, err := connectortesting.NewFileGitConnector(harness.TempDir)
	require.NoError(t, err)
	harness.RegisterConnector(fileGit)
	harness.BindFamily("git", fileGit.Key())

	// Add mock policy and webhook connectors
	mockPolicy := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "policy")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"allowed":    true,
					"violations": []interface{}{},
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockPolicy)
	harness.BindFamily("policy", mockPolicy.Key())

	mockWebhook := &connectortesting.MockConnector{
		BaseConnector: func() connector.BaseConnector {
			base, _ := connector.NewBaseConnector(connector.ConnectorTypeOther, "webhook")
			return base
		}(),
		ExecuteFunc: func(ctx context.Context, operation string, input map[string]interface{}) (*connector.ConnectorResult, error) {
			return &connector.ConnectorResult{
				Status: connector.StatusSuccess,
				Output: map[string]interface{}{
					"status_code":   200,
					"response_body": "ok",
				},
			}, nil
		},
	}
	harness.RegisterConnector(mockWebhook)
	harness.BindFamily("webhook", mockWebhook.Key())

	params := loadParamsFixture(t, "infra-vm-app")
	// Add required parameters for the module
	params["infra_repo"] = "tenant-vm-app/workload"
	params["callback_url"] = "http://example.com/callback"
	params["job_id"] = "test-job-id"
	params["idempotency_key"] = "infra-it-vm-app-1"

	// Create repository and status file BEFORE job runs so health polling succeeds
	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-vm-app/workload"})
	require.NoError(t, err)
	// Create a mock .status.yaml file that will be found by health polling
	// Calculate expected commit SHA that will be generated by fileGit connector
	// Format: "{repo}-{branch}-{filesWritten}" where filesWritten = 1 (single manifest)
	expectedCommitSHA := fmt.Sprintf("%s-%s-%d", "tenant-vm-app/workload", "main", 1)
	statusContent := fmt.Sprintf(`status: healthy
timestamp: %s
commit_sha: %s
resources:
  - type: cluster
    arn: arn:aws:eks:eu-west-1:123456789012:cluster/test-cluster
    id: test-cluster-id`, time.Now().Format(time.RFC3339), expectedCommitSHA)
	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-vm-app/workload",
		"path":      ".status.yaml",
		"content":   statusContent,
	})
	require.NoError(t, err)

	jobID := harness.CreateJob(JobOptions{
		TenantID:       "tenant-vm-app",
		PathKey:        infra.ModuleKey,
		IdempotencyKey: "infra-it-vm-app-1",
		Params:         params,
	})

	require.NoError(t, harness.RunSchedulerCycle())
	require.NoError(t, harness.WaitForJobState(jobID, "succeeded", 5*time.Second))

	manifest := fetchLatestManifestYAML(t, harness, jobID)
	exportManifestForVisualValidation(t, "infra-vm-app.manifest.yaml", manifest)

	validator := NewCrossplaneValidator(
		FieldPresenceRule{fields: []string{"apiVersion", "kind", "metadata", "spec"}},
		PlatformTenantLabelRule{},
		SpecRule{},
	)
	require.NoError(t, validator.ValidateYAML([]byte(manifest)))
	require.Contains(t, manifest, "kind: XVirtualMachine")
	require.Contains(t, manifest, "name: vm-aws")
	require.Contains(t, manifest, "kind: XVPCNetwork")
	require.Contains(t, manifest, "name: vpc-aws")
	require.NotContains(t, manifest, "kind: XKubernetesCluster")

	// Compare against golden file for regression protection
	AssertGoldenYAML(t, "infra-vm-app", []byte(manifest))

	_, err = fileGit.Execute(context.Background(), "create_repository", map[string]interface{}{"repo_path": "tenant-vm-app/workload"})
	require.NoError(t, err)
	_, err = fileGit.Execute(context.Background(), "create_or_update_file", map[string]interface{}{
		"repo_path": "tenant-vm-app/workload",
		"path":      "infra/manifest.yaml",
		"content":   manifest,
	})
	require.NoError(t, err)
}

func loadParamsFixture(t *testing.T, name string) map[string]any {
	t.Helper()
	path := filepath.Join("testdata", "payloads", fmt.Sprintf("%s.yaml", name))
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	params := map[string]any{}
	require.NoError(t, yaml.Unmarshal(data, &params))
	return params
}

func exportManifestForVisualValidation(t *testing.T, fileName, manifest string) {
	t.Helper()
	outDir := filepath.Join("testdata", "output")
	require.NoError(t, os.MkdirAll(outDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, fileName), []byte(manifest), 0o644))
}

func fetchLatestManifestYAML(t *testing.T, harness *IntegrationTestHarness, jobID string) string {
	t.Helper()
	conn, err := harness.Pool.Acquire(context.Background())
	require.NoError(t, err)
	defer conn.Release()

	// Debug: list all steps for this job
	rows, _ := conn.Query(context.Background(), `
		SELECT step_key, status, output_json IS NOT NULL as has_output, error_code, error_message
		FROM steps
		WHERE job_id = $1::uuid
		ORDER BY attempt, id
	`, jobID)
	if rows != nil {
		for rows.Next() {
			var stepKey, status, errorCode, errorMessage string
			var hasOutput bool
			_ = rows.Scan(&stepKey, &status, &hasOutput, &errorCode, &errorMessage)
			t.Logf("Step: %s, status: %s, has_output: %v, error: %s %s", stepKey, status, hasOutput, errorCode, errorMessage)
		}
		rows.Close()
	}

	var manifest string
	err = conn.QueryRow(context.Background(), `
		SELECT output_json->>'manifest_yaml'
		FROM steps
		WHERE job_id = $1::uuid
		  AND step_key = 'infra.render'
		ORDER BY attempt DESC, id DESC
		LIMIT 1
	`, jobID).Scan(&manifest)
	require.NoError(t, err)
	return manifest
}

func requeueJobForRetry(t *testing.T, harness *IntegrationTestHarness, jobID string) {
	t.Helper()
	conn, err := harness.Pool.Acquire(context.Background())
	require.NoError(t, err)
	defer conn.Release()

	_, err = conn.Exec(context.Background(), `
		UPDATE jobs
		SET state = 'queued',
			owner_id = NULL,
			lease_expires_at = NULL,
			next_run_at = now() - interval '1 second',
			updated_at = now()
		WHERE id = $1::uuid
	`, jobID)
	require.NoError(t, err)
}

// PlatformTenantLabelRule validates labels used by infra XR manifests.
type PlatformTenantLabelRule struct{}

func (PlatformTenantLabelRule) Name() string { return "PlatformTenantLabel" }

func (PlatformTenantLabelRule) Validate(obj map[string]any) error {
	metadata, ok := obj["metadata"].(map[string]any)
	if !ok {
		return fmt.Errorf("metadata must be an object")
	}
	labels, ok := metadata["labels"].(map[string]any)
	if !ok {
		return fmt.Errorf("metadata.labels must be defined")
	}
	if _, ok := labels["platform.io/tenant"]; !ok {
		return fmt.Errorf("metadata.labels must include platform.io/tenant")
	}
	return nil
}
